const contact = {
    "ADD_CONTACT_BEGIN":"ADD_CONTACT_BEGIN",
    "ADD_CONTACT_COMPLETE":"ADD_CONTACT_COMPLETE",
    "ADD_CONTACT_ERROR":"ADD_CONTACT_ERROR"
};
const engagement = {
    "FETCH_ENGAGEMENT_BEGIN":"FETCH_ENGAGEMENT_BEGIN",
    "FETCH_ENGAGEMENT_COMPLETE":"FETCH_ENGAGEMENT_COMPLETE",
    "FETCH_ENGAGEMENT_ERROR":"FETCH_ENGAGEMENT_ERROR"
}
const ActionTypeRepo = {
    contact,
    engagement
}
export default ActionTypeRepo;

